### ISSUE TITLE
Deprecated python2.7 > Upgrade to 3.9

### ISSUE THREAD

**Issue by JustinDPerkins** [aws-samples/aws-gamelift-sample#19]
When deploying the CFT template, it fails due to the deprecated python version2.7.

**Comment by jinspark-lab** [comment]
Thanks for your feedback. We are preparing a version update for this sample with the latest best practices. :) 
I will update it ASAP.

**Comment by jinspark-lab** [comment]
It has been solved from the update (https://github.com/aws-samples/aws-gamelift-sample/commit/2141682e7c15f270afa34e8978ac634c2c23bbf8).
Resolved.
